package com.hk.svr.pub;

public interface Err {

	int SUCCESS = 0;

	int BOX_BOXKEY_DATA_ERROR = 1;// 数据格式错误

	int BOX_BOXKEY_IS_SYS_KEY = 2;// 关键字成为系统关键字

	int LOGIN_SUCCESS = 4;// 登录成功

	int LOGIN_FAIL = 5;// 登录失败

	int CONTENTFILTER = 6;// 含有敏感词

	int NICKNAME_ERROR = 7;// 昵称数据错误

	int PASSWORD_DATA_ERROR = 10;// 密码字符错误

	int BIRTHDAY_MONTH_ERROR = 11;

	int BIRTHDAY_DATE_ERROR = 12;

	int TAG_NAME_ERROR = 13;

	int COMPANY_NAME_ERROR = 14;

	int COMPANY_ADDR_LEN_TOOLONG = 15;

	int COMPANY_TRAFFIC_LEN_TOOLONG = 16;

	int COMPANY_TEL_LEN_TOOLONG = 17;

	int COMPANY_OPTEL_LEN_TOOLONG = 18;

	int COMPANY_NAME_LEN_TOOLONG = 19;

	int COMPANY_OPNAME_LEN_TOOLONG = 20;

	int COMPANY_KIND_ERROR = 21;

	// int COMPANY_PWD_NOTEQUAL = 22;
	// int COMPANY_PWD_ERROR = 23;
	int COMPANYTAG_NAME_ERROR = 24;

	int COMPANYTAG_KIND_ERROR = 25;

	int COMPANY_SIGN_LEN_NOTIN_RANGE = 26;

	int COMPANY_INTRO_LEN_TOOLONG = 27;

	/*                                                                                                                                                                                                                                                                                                                                                         ***************************** company end ****************************** */
	int BIZCIRCLE_NAME_ERROR = 28;

	int BIZCIRCLE_NAME_LEN_TOOLONG = 29;

	int BIZCIRCLE_CITYID_ERROR = 30;

	int BUILDINGTAG_CITYID_ERROR = 31;

	int BUILDINGTAG_NAME_ERROR = 32;

	int BUILDINGTAG_LEN_TOOLONG = 33;

	int INFORMATION_NAME_ERROR = 34;

	int INFORMATION_NAME_LEN_TOOLONG = 35;

	int INFORMATION_TAG_ERROR = 36;

	int INFORMATION_TAG_LEN_TOOLONG = 37;

	int USERID_ERROR = 38;

	int LABA_CONTENT_ERROR = 39;

	int LABA_CONTENT_LEN_TOOLONG = 40;

	int INFROMATION_INTRO_LEN_TOOLONG = 41;

	int BOX_NAME_ERROR = 42;

	int BOX_TOTALCOUNT_OUT_OF_LENGTH = 43;

	int BOX_BEGINTIME_ERROR = 44;

	int BOX_ENDTIME_ERROR = 45;

	int BOX_TIME_ERROR = 46;

	int BOX_CONTENT_LENG_TOO_LONG = 47;

	int BOXPRIZE_NAME_LENGTH_TOO_LONG = 48;

	int BOXPRIZE_TIP_LENGTH_TOO_LONG = 49;

	int BOXPRIZE_COUNT_ERROR = 50;

	int BOXPRIZE_TIP_ERROR = 51;

	int BOX_BOXTYPE_ERROR = 52;

	int USERCARD_HOMEPOSTCODE_LENGTH_TOO_LONG = 53;

	int USERCARD_WORKADDR_LENGTH_TOO_LONG = 54;

	int USERCARD_WORKPOSTCODE_LENGTH_TOO_LONG = 55;

	int USERCARD_INTRO_LENGTH_TOO_LONG = 56;

	int USERCARD_WORKPLACE_LENGTH_TOO_LONG = 57;

	int USERCARD_JOBRANK_LENGTH_TOO_LONG = 58;

	int USERCARD_MAINMOBILE_LENGTH_TOO_LONG = 59;

	int USERCARD_ANOTHERMOBILE_LENGTH_TOO_LONG = 60;

	int USERCARD_HOMETELPHONE_LENGTH_TOO_LONG = 61;

	int USERCARD_EMAIL_LENGTH_TOO_LONG = 62;

	int USERCARD_QQ_LENGTH_TOO_LONG = 63;

	int USERCARD_MSN_LENGTH_TOO_LONG = 64;

	int USERCARD_GTALK_LENGTH_TOO_LONG = 65;

	int USERCARD_SKYPE_LENGTH_TOO_LONG = 66;

	int USERCARD_HOMEADDR_LENGTH_TOO_LONG = 67;

	int USERCARD_WORKPLACEWEB_LENGTH_TOO_LONG = 68;

	int CHGCARDACT_NAME_ERROR = 69;

	int CHGCARDACT_NAME_LENGTH_TOO_LONG = 70;

	int CHGCARDACT_PERSISTHOUR_TOO_BIG = 71;

	int TAG_NMAE_LENGTH_TOO_LONG = 72;

	int COMPANY_REVIEW_CONTENT_LENGTH_TOO_LONG = 73;

	int COMPANY_SCORE_ERROR = 74;

	// int COMPANY_ID_ERROR = 75;
	int COMPANY_REVIEW_CONTENT_ERROR = 76;

	int PHOTO_NAME_LENGTH_TOO_LONG = 77;

	int AUTHCOMPANY_CONTENT_ERROR = 78;

	int AUTHCOMPANY_CONTENT_LENGTH_TOO_LONG = 79;

	int AUTHCOMPANY_CHECKSTATUS_ERROR = 80;

	int ADMINHKB_CONTENT_LENGTH_TOO_LONG = 81;

	int ADMINHKB_MONEY_ERROR = 82;

	int USER_NAME_ERROR = 84;

	int BOX_PRECOUNT_ERROR = 85;

	int HKOBJID_ERROR = 86;

	int COMPANYMONEY_ENDTIME_ERROR = 87;

	int COMPANYMONEY_MONEY_ERROR = 88;

	int ACT_NAME_ERROR = 89;

	int ACT_NAME_LENGTH_TOO_LONG = 90;

	int ACT_BEGINTIME_ERROR = 91;

	int ACT_ENDTIME_ERROR = 92;

	int ACT_ADDR_LENGTH_TOO_LONG = 93;

	int ACT_INTRO_LENGTH_TOO_LONG = 94;

	int ACT_NEEDCHECK_ERROR = 95;

	int ACT_ENDTIME_EARLYER_THAN_BEGINTIME_ERROR = 96;

	int USERSMS_MSGID_ERROR = 97;

	int USERSMS_CONTENT_ERROR = 98;

	int USERSMS_CONTENT_LENGTH_TOO_LONG = 99;

	int REGCODE_NAME_ERROR = 100;

	int CMPPRODUCTSORT_NAME_ERROR = 101;

	int CMPPORDUCTSORT_NAME_LENGTH_TOO_LONG = 102;

	int CMPPRODUCT_NAME_ERROR = 103;

	// int CMPPRODUCT_NAME_LENGTH_TOO_LONG = 104;
	int CMPPRODUCT_SORTID_ERROR = 105;

	int CMPPRODUCT_INTRO_LENGTH_TOO_LONG = 106;

	int CMPPRODUCT_MONEY_ERROR = 107;

	int CMPPRODUCT_REBATE_ERROR = 108;

	int USEROTHERINFO_INTRO_LENGTH_TOO_LONG = 110;

	int USEROTHERINFO_SEX_ERROR = 111;

	int CMPCOMMENT_CONTENT_ERROR = 112;

	int CMPCOMMENT_CONTENT_LENGTH_TOO_LONG = 113;

	int USEROTHERINFO_EMAIL_ERROR = 114;

	int COMPANY_TRAFFIC_ERROR = 115;

	int AUTHCOMPANY_REMARK_LENGTH_TOO_LONG = 116;

	int APIUSER_NAME_ERROR = 117;

	int APIUSER_URL_ERROR = 118;

	int SESSIONKEY_OVERTIME = 119;

	int APIUSER_UNAVAILABLE = 120;

	int NOOBJECT_ERROR = 121;

	int USER_OLDPASSWORD_ERROR = 122;

	int USEROTHERINFO_BIRTHDAY_ERROR = 123;

	int NICKNAME_DUPLICATE = 124;

	int LABA_CAN_NOT_REPLY_YOURSELF = 125;

	int LABA_REFLABA_EXIST = 126;

	int USER_NOT_FOLLOW = 127;

	// int NODATA = 128;
	int MSG_CONTENT_ERROR = 129;

	int CMPBULLETIN_CONTENT_LENGTH_TOO_LONG = 130;

	int CMPBULLETIN_CONTENT_ERROR = 131;

	int COMPANY_NOT_AUTH = 132;

	int CMPBULLETIN_TITLE_ERROR = 133;

	int CMPBULLETIN_TITLE_LENGTH_TOO_LONG = 134;

	int USERTOOL_LABARTFLG_ERROR = 135;

	int IMG_UPLOAD_ERROR = 136;

	int IMG_FMT_ERROR = 137;

	int COMPANY_ZONE_ERROR = 138;

	int COMPANY_NAME_DUPLICATE = 139;

	int COMPANY_CANNOT_UPDATE = 140;

	int CMPRECRUIT_CONTENT_LENGTH_TOO_LONG = 141;

	int CMPRECRUIT_TITLE_ERROR = 142;

	int CMPRECRUIT_TITLE_LENGTH_TOO_LONG = 143;

	int CMPRECRUIT_CONTENT_ERROR = 144;

	int EMAIL_ERROR = 145;

	int MOBILE_ERROR = 146;

	int EMAIL_ALREADY_EXIST = 147;

	int MOBILE_ALREADY_EXIST = 148;

	int USERTOOL_SHOWREPLY_ERROR = 149;

	int CMPMODULE_TITLE_ERROR = 150;

	int CMPMODULE_TITLE_LENGTH_TOO_LONG = 151;

	int CMPMODULE_INTRO_LENGTH_TOO_LONG = 152;

	int COUPON_NAME_ERROR = 153;

	int COUPON_NAME_LENGTH_TOO_LONG = 154;

	int COUPON_CONTENT_LENGTH_TOO_LONG = 155;

	int COUPON_REMARK_LENGTH_TOO_LONG = 156;

	int COUPON_LIMITDAY_ERROR = 157;

	int COUPON_ENDTIME_ERROR = 158;

	int COUPON_AMOUNT_ERROR = 159;

	int COMPANYPHOTO_OUT_OF_COUNT = 160;

	int COUPON_REMAIN_EMPTY = 161;

	int USEROTHERINFO_MOBILE_NOT_BIND = 162;

	int EMAIL_SEND_ERROR = 163;

	int CMPADMINHKBLOG_ADDCOUNT_ERROR = 164;

	int MOBILE_CMP_NOT_MOBILE = 165;

	int PROUSER_NICKNAME_ERROR = 166;

	int PROUSER_INTRO_ERROR = 167;

	int PROUSER_MOBILE_ERROR = 168;

	int PROUSER_EMAIL_ERROR = 169;

	int IMPRESSION_CONTENT_ERROR = 170;

	int LOGIN_USER_OR_PASSWORD_ERROR = 171;

	int REG_INPUT_REGCODE = 172;// 输入注册码

	int REG_MUST_AGREE = 173;// 必须同意火酷协议

	int REG_2_PASSWORD_NOT_SAME = 174;// 2次密码不一致

	int SEX_ERROR = 175;

	int MOBILE_OR_EMAIL_INPUT = 176;// 手机号或E-mail至少输入一个

	int HKOBJARTICLE_SUBMIT_HKUSER_MUST_LOGIN = 177;// 必须登录才能提交

	int HKOBJARTICLE_TITLE_ERROR = 178;

	int HKOBJARTICLE_URL_ERROR = 179;

	int HKOBJARTICLE_AUTHORFLG_ERROR = 180;

	int HKOBJARTICLE_AUTHOR_ERROR = 181;

	int HKOBJARTICLE_EMAIL_ERROR = 182;

	int HKOBJARTICLE_TEL_ERROR = 183;

	int HKOBJARTICLE_BLOG_ERROR = 184;

	int AUTHORAPPLY_CONTENT_ERROR = 185;

	int AUTHORAPPLY_NAME_ERROR = 186;

	int AUTHORAPPLY_BLOG_ERROR = 187;

	int AUTHORAPPLY_EMAIL_ERROR = 188;

	int AUTHORAPPLY_TEL_ERROR = 189;

	int MSG_MSG_ERROR = 190;

	int HKOBJORDER_STOPFLG_ERROR = 191;

	int HKOBJORDER_MONEY_ERROR = 192;

	int HKOBJORDER_KIND_ERROR = 193;

	int HKOBJORDER_PDAY_ERROR = 195;

	int ZONE_ERROR = 196;

	int HKOBJKEYTAGORDER_TAGID_ERROR = 197;

	int HKOBJKEYTAGORDER_PDAY_ERROR = 198;

	int HKOBJKEYTAGORDER_MONEY_ERROR = 199;

	int HKOBJKEYTAGORDER_STOPFLG_ERROR = 200;

	int COMPANYKINDID_ERROR = 201;

	int HKOBJORDERDEF_HKB_ERROR = 202;

	int HKOBJORDERDEF_KIND_ERROR = 203;

	int KEYTAGID_ERROR = 204;

	int KEYTAG_HKB_ERROR = 205;

	int NOENOUGH_MONEY = 206;

	int SMALLERTHAN_MINMONEY = 207;

	int HKOBJORDER_PDAY_EARLIER_THAN_NOW = 208;// 早于当期啊时间

	int ORDER_DATA_ALREADY_UPDATE = 209;// 已经更新过此数据

	int HKOBJKINDORDER_MONEY_ERROR = 210;

	int HKOBJKINDORDER_PDAY_ERROR = 211;

	int HKOBJKINDORDER_STOPFLG_ERROR = 212;

	int CMPGROUP_NAME_ERROR = 213;

	int CMPGROUP_INTRO_ERROR = 214;

	int CMPGROUP_VALIDATEFLG_ERROR = 215;

	int CMPPRODUCT_NAME_DUPLICATE = 216;

	int CMPPORDUCTSORT_NAME_DUPLICATE = 217;

	int NOENOUGH_GROUND = 218;

	int IMAGE_OP_ERROR = 219;

	int CMPPRODUCTPHOTO_NAME_ERROR = 220;

	int COMPANYKIND_PARENTID_ERROR = 221;

	int COMPANYKIND_NAME_ERROR = 222;

	int COMPANYKIND_NAME_DUPLICATE = 223;

	int CMPCHILDKIND_KINDID_ERROR = 224;

	int CMPCHILDKIND_NAME_ERROR = 225;

	int CMPCHILDKIND_NAME_DUPLICATE = 226;

	int IMG_OUTOFSIZE_ERROR = 227;

	int MSG_CANNOT_SEND_FORNOTFOLLOW = 228;

	int FOLLOW_USER_BLOCK = 229;

	int USER_NOT_LOGIN = 230;

	int TAG_ALREADY_EXIST = 231;

	int MSN_ERROR = 232;

	int MSN_ALREADY_EXIST = 233;

	int PASSWORD_OLD_ERROR = 234;

	int PWD_PROTECT_ERROR = 235;

	int NOENOUGH_HKB = 236;

	int BOX_BOXKEY_ALREADY_EXIST = 237;

	int BOXPRIZE_OUT_OF_TOTALCOUNT = 238;

	int BOX_OPENOUT = 239;

	int BOX_EXPIRED = 240;

	int BOX_STOP = 241;

	int BOX_PAUSE = 242;

	int BOX_OUT_OF_LIMIT = 243;

	int CMPPHOTO_OUT_OF_LIMIT = 244;

	int CMPPRODUCTPHOTO_OUT_OF_LIMIT = 245;

	int USER_NOT_EXIST = 246;

	int EMAIL_SENDCOUNT_LIMIT = 247;

	int FGTPWD_EMAIL_SEND_OK = 248;

	int FGTPWD_PROTECT_INPUT = 249;

	int FGTPWD_PROTECT_ERROR = 250;

	int CMPMEMBERGRADE_NAME = 251;

	int MONEY_ERROR = 252;

	int MONEY_BALANCE_NOT_ENOUGH = 253;

	int ORDERFORM_ORDERTIME_ERROR = 254;

	int ORDERFORM_CONTENT_ERROR = 255;

	int TEL_ERROR = 256;

	int CMPPRODUCT_PNUM_ERROR = 257;

	int CMPPRODUCT_SHORTNAME_ERROR = 258;

	int CMPTABLESORT_NAME_ERROR = 259;

	int CMPTABLE_TABLENUM_ERROR = 260;

	int CMPTABLE_INTRO_ERROR = 261;

	int CMPTABLESORT_NAME_DUPLICATE = 262;

	int CMPTABLE_TABLENUM_DUPLICATE = 263;

	int CMPTABLE_BESTPERSONNUM_ERROR = 264;

	int CMPTABLE_MOSTPERSONNUM_ERROR = 265;

	int CMPTABLE_OPNAME_ERROR = 266;

	int CMPTABLE_NETORDERFLG_ERROR = 267;

	int CMPTABLE_SORTID_ERROR = 268;

	int CMPTABLEPHOTO_OUT_OF_LIMIT = 269;

	int TIME_ERROR = 270;

	int CMPORDERTABLE_PERSONNUM_ERROR = 271;

	int CMPORDERTABLE_NAME_RROR = 272;

	int CMPORDERTABLE_REMARK_ERROR = 273;

	int CMPTABLE_NOTEXIST = 274;

	int CMPTABLEPHOTOSET_TITLE_ERROR = 275;

	int CMPTABLEPHOTOSET_INTRO_ERROR = 276;

	int CMPTABLEPHOTO_NMAE_ERROR = 277;

	int CMPUNION_DOMAIN_DUPLICATE = 278;

	int CMPUNION_WEBNAME_DUPLICATE = 279;

	int CMPUNION_NAME_ERROR = 280;

	int CMPUNION_INTRO_ERROR = 281;

	int CMPUNION_TRAFFIC_ERROR = 282;

	int CMPUNION_ADDR_ERROR = 283;

	int CMPUNION_WEBNAME_ERROR = 284;

	int CMPUNIONKIND_NAME_ERROR = 285;

	int CMPUNIONKIND_NAME_DUPLICATE = 286;

	int CMPUNION_ZONE_ERROR = 287;

	int CMPUNIONBOARD_TITLE_ERROR = 288;

	int CMPUNIONBOARD_CONTENT_ERROR = 289;

	int CMPUNIONLINK_TITLE_ERROR = 290;

	int CMPUNIONLINK_URL_ERROR = 291;

	int CMPACT_NAME_ERROR = 292;

	int CMPACT_KINDID_ERROR = 293;

	int CMPACT_INTRO_ERROR = 294;

	int CMPACT_SPINTRO_ERROR = 295;

	int CMPACT_BEGINTIME_ERROR = 296;

	int CMPACT_ENDTIME_ERROR = 297;

	int CMPACT_TIME_ERROR = 298;

	int CMPACT_ADDR_ERROR = 299;

	int CMPACT_PCITYID_ERROR = 300;

	int CMPACTCMT_CONTENT_ERROR = 301;

	int CMPACTCOST_NAME_ERROR = 302;

	int CMPACTCOST_INTRO_ERROR = 303;

	int CMPACTKIND_NAME_ERROR = 304;

	int CMPACTSTEPCOST_USERCOUNT_ERROR = 305;

	int CMPACTSTEPCOST_ACTCOST_ERROR = 306;

	int CMPACTKIND_NAME_DUPLICATE = 307;

	int CMDDATA_NAME_DUPLICATE = 308;

	int CMDDATA_NAME_ERROR = 309;

	int CMPACTCOST_ACTCOST_ERROR = 310;

	int LABACMT_CONTENT_ERROR = 311;

	int ORDERFORMUSERINFO_TITLE_ERROR = 312;

	int ZONE_NOT_EXIST = 313;

	int REG_INPUT_VALIDATECODE = 314;

	int CMPTIP_CONTENT_ERROR = 315;

	int CMPTIP_LINK_ERROR = 316;

	int CMPTAG_NAME_ERROR = 317;

	int CMPTAGREF_EXIST = 318;

	int CHECKIN_PCITYID_ERROR = 319;

	int CMPADMINGROUP_NAME_DUPLICATE = 320;

	int CMPADMINGROUP_NAME_ERROR = 321;

	int ZONE_COUNTRY_NAME_DUPLICATE = 322;

	int ZONE_PROVINCE_NAME_DUPLICATE = 323;

	int ZONE_CITY_NAME_DUPLICATE = 324;

	int BADGE_NAME_ERROR = 325;

	int BADGE_INTRO_ERROR = 326;

	int COMPANY_UNIONKINDID_ERROR = 327;

	int ZONE_CITY_NOTFOUND = 328;

	int ZONE_PROVINCE_NOTFOUND = 329;

	int USER_DOMAIN_ERROR = 330;

	int USER_DOMAIN_DUPLICATE = 331;

	int NICKNAME_ERROR2 = 332;// 昵称数据错误

	int USER_DOMAIN_ERROR2 = 333;

	int USER_DOMAIN_ERROR3 = 334;// 关键词，不能使用

	int PHOTOCMT_CONTENT_ERROR = 335;// 图片评论字数不能为空或者多于200字

	int EMAIL_ALREADY_EXIST2 = 336;

	int LABATAG_OUTOF_LIMIT = 337;

	int CHECKIN_SPEED_TOO_FAST = 338;

	int SMS_SENDCOUNT_OUT_OF_LIMIT = 339;

	int USERFGTSMS_SMSCODE_ERROR = 340;

	int USER_STOP = 341;

	int USER_LOGIN_PASSWOR_ERROR = 342;

	int USER_LOGIN_INPUT_EMPTY = 343;

	int USER_LOGIN_NO_EMAIL = 344;

	int USER_LOGIN_NO_MOBILE = 345;

	int USER_LOGIN_MUST_INPUT_EMAIL_OR_MOBILE = 346;

	int BOXPRIZE_OUT_OF_REMAIN_LIMIT = 347;

	int BOX_NOENOUGH_HKB_CREATEBOX = 349;

	int ZONE_NAME_ERROR = 350;

	int OPENBOX_CITY_ERROR = 351;

	int INVITECODE_ERROR = 352;

	int INVITECODE_EXPIRED = 353;

	int COUPON_AMOUNT_LESSTHAN_DCOUNT = 354;

	int HKAD_TOTALVIEWCOUNT_LESSTHAN_VIEWCOUNT = 355;

	int HKAD_NAME_ERROR = 356;

	int HKAD_TOTALVIEWCOUNT_ERROR = 357;

	int HKAD_HREF_ERROR = 358;

	int HKAD_NOENOUGH_HKB_VIEW = 359;

	int HKAD_FILE_ERROR = 360;

	int HKAD_ADDATA_ERROR = 361;

	int CMPBBS_TITLE_ERROR = 362;

	int CMPBBSCONTENT_CONTENT_ERROR = 363;

	int UPLOAD_ERROR = 364;

	int CMPNAV_NAME_ERROR = 365;

	int CMPARTICLE_TITLE_ERROR = 366;

	int CMPARTICLE_CONTENT_ERROR = 367;

	int CMPCONTACT_QQ_ERROR = 368;

	int CMPSELLNET_NAME_ERROR = 369;

	int CMPSELLNET_TEL_ERROR = 370;

	int CMPSELLNET_ADDR_ERROR = 371;

	int CMPJOININAPPLY_NAME_ERROR = 372;

	int CMPJOININAPPLY_CMPNAME_ERROR = 373;

	int CMPJOININAPPLY_TEL_ERROR = 374;

	int CMPJOININAPPLY_MOBILE_ERROR = 375;

	int CMPJOININAPPLY_CONTENT_ERROR = 376;

	int CMPMSG_NAME_ERROR = 377;

	int CMPMSG_TEL_ERROR = 378;

	int CMPMSG_CONTENT_ERROR = 379;

	int CMPBBSKIND_NAME_ERROR = 380;

	int CMPBBSKIND_NAME_DUPLICATE = 381;

	int ONLY_PIC_UPLOAD = 382;

	int MUST_PIC_UPLOAD = 384;

	int CMPBBSREPLY_CONTENT_ERROR = 385;

	int CMPNAV_SHOWFLG_ERROR = 386;

	int CMPNAV_REFFUNC_ERROR = 387;

	int UPLOAD_ERROR2 = 388;

	int CMPCONTACT_QQHTML_ERROR = 389;

	int CMPPRODUCTSORT_NAME_DUPLICATE = 390;

	int BOXKEY_TOTALCOUNT_SMALLER_THAN_PRIZETOTALCOUNT = 391;

	int BOXPRIZE_COUNT_MORE_THAN_BOXREMAINCOUNT = 392;

	int BOX_CITYID_ERROR = 393;

	int USER_NOT_CMPADMINUSER = 394;

	int COMPANY_UPLOAD_LOGO_IMGWIDTH_OUTOFSIZE = 395;

	int IMG_UPLOAD_FMT_ERROR_NUM = 396;

	int IMG_UPLOAD_OUTOFSIZE_ERROR_NUM = 397;

	int IMG_OUTOFSIZE_ERROR_FOR_SIZE = 398;

	int CMPBBS_KINDID_ERROR = 398;

	int EPP_EMAIL_ALREADY_EXIST = 399;

	int PASSWORD_CONFIRM_ERROR = 400;

	int CMPFRLINK_NAME_ERROR = 401;

	int CMPFRLINK_URL_ERROR = 402;

	int CMPAD_IMAGE_WIDTH_ERROR = 403;

	int CMPAD_NAME_ERROR = 404;

	int CMPAD_URL_ERROR = 405;

	int CMPINFO_NOT_EXIST = 406;

	int CMPNAV_FILESHOWLINK_ERROR = 407;

	int CMPSELLNETKIND_NAME_ERROR = 408;

	int CMPPRODUCTSORTATTRMODULE_ATTRNAME_ERROR = 409;

	int CMPPRODUCTSORTATTR_NAME_ERROR = 410;

	int CMPHOMEPICAD_TITLE_ERROR = 411;

	int CMPHOMEPICAD_URL_ERROR = 412;

	int CMPPRODUCTSORTFILE_NAME_ERROR = 413;

	int CMPPRODUCTSORTFILE_URL_ERROR = 414;

	int CMPNAV_REFFUNC_BBS_EXIST = 415;

	int CMPNAV_REFFUNC_PRODUCT_EXIST = 416;

	int CMPDOWNFILE_NAME_ERROR = 417;

	int CMPARTICLEGROUP_NAME_ERROR = 418;

	int UPLOAD_FILE_EMPTY = 419;

	int UPLOAD_FILE_SIZE_LIMIT = 420;

	int CMPVIDEO_NAME_ERROR = 421;

	int CMPVIDEO_HTML_ERROR = 422;

	int CMPVIDEO_INTRO_ERROR = 423;

	int CMPVIDEO_FILE_OR_HTML_EMPTY = 424;

	int CMPOTHERWEBINFO_NO_FILESIZE = 425;

	int CMPPAGEBLOCK_NAME_ERROR = 426;

	int CMPPAGEBLOCK_PAGEMODID_ERROR = 427;

	int CMPADBLOCK_DUPLICATE_ERROR = 428;

	int CMPPAGEBLOCK_DATA_LIMIT = 429;

	int CMPARTICLEBLOCK_DUPLICATE_ERROR = 430;

	int CMPADGROUP_NAME_ERROR = 431;

	int CMPADGROUP_NAME_DUPLICATE = 432;

	int CMPARTICLEGROUP_NAME_DUPLICATE = 433;

	int CMPAD_HTML_ERROR = 434;

	int CMPORGARTICLE_TITLE_ERROR = 435;

	int CMPORGARTICLE_CONTENT_ERROR = 436;

	int CMPORG_NAME_ERROR = 437;

	int CMPORGNAV_NAME_ERROR = 438;

	int CMPORGSTUDYAD_TITLE_ERROR = 439;

	int CMPORGSTUDYAD_SCHOOLNAME_ERROR = 440;

	int CMPORGSTUDYAD_STUDYADDR_ERROR = 441;

	int CMPORGSTUDYAD_STUDYUSER_ERROR = 442;

	int CMPORGSTUDYAD_TEACHTYPE_ERROR = 443;

	int CMPORGSTUDYAD_PRICE_ERROR = 444;

	int CMPORGSTUDYAD_AVAILABLETIME_ERROR = 445;

	int CMPORGSTUDYAD_BEGINTIME_ERROR = 446;

	int CMPORGSTUDYADCONTENT_CONTENT_ERROR = 447;

	int CMPORGMSG_NAME_ERROR = 448;

	int CMPORGMSG_TEL_ERROR = 449;

	int CMPORGMSG_CONTENT_ERROR = 450;

	int CMPORGMSG_EMAIL_ERROR = 451;

	int CMPORGMSG_IM_ERROR = 452;

	int CMPORGAPPLY_ORGNAME_ERROR = 453;

	int CMPORGAPPLY_TEL_ERROR = 454;

	int CMPORGAPPLY_EMAIL_ERROR = 455;

	int CMPORGAPPLY_USERNAME_ERROR = 456;

	int CMPORGSTUDYADUSER_NAME_ERROR = 457;

	int CMPORGSTUDYADUSER_TEL_ERROR = 458;

	int CMPORGSTUDYADUSER_MOBILE_ERROR = 459;

	int CMPORGSTUDYADUSER_EMAIL_ERROR = 460;

	int CMPORGSTUDYADUSER_IM_ERROR = 461;

	int CMPORGSTUDYADUSER_CITY_ERROR = 462;

	int CMPORGSTUDYADUSER_MSG_ERROR = 463;

	int IMG_VALIDATE_CODE_ERROR = 464;

	int CMPORGSTUDYADUSER_GENDER_ERROR = 465;

	int CMPORGSTUDYADUSER_TEL_MOBILE_ERROR = 466;

	int CMPSTUDYKIND_NAME_ERROR = 467;

	int CMPINFO_ARTICLEAD_ERROR = 468;

	int CMPINFO_COLUMNAD_ERROR = 469;

	int CMPACTORROLE_NAME_ERROR = 470;

	int CMPACTOR_NAME_ERROR = 471;

	int CMPPHOTOSET_NAME_ERROR = 472;

	int CMPACTOR_INTRO_ERROR = 473;

	int CMPSVR_NAME_ERROR = 474;

	int CMPSVR_INTRO_ERROR = 475;

	int CMPSVRKIND_NAME_ERROR = 476;

	int CMPACTORSPTIME_TIME_ERROR = 477;

	int CMPNAV_TITLE_ERROR = 478;

	int CMPNAV_INTRO_ERROR = 479;

	int CMPNAV_BGIMG_ERROR = 480;

	int CMPNAV_BGIMG_UPLOAD_ERROR = 481;

	int CMPINFO_BGIMG_ERROR = 482;

	int CMPINFO_BGIMG_UPLOAD_ERROR = 483;

	int CMPNAV_URL_ERROR = 484;

	int CMPINFO_CPINFO_ERROR = 485;

	int COMPANY_LOGO_FILE_BIGGER_ERROR = 486;

	int COMPANY_LOGO2_FILE_BIGGER_ERROR = 487;

	int COMPANY_LOGO_FILE_UPLOAD_ERROR = 488;

	int COMPANY_LOGO2_FILE_UPLOAD_ERROR = 489;

	int COMPANY_LOGO_FILE_MUST_IMG_ERROR = 490;

	int COMPANY_LOGO2_FILE_MUST_IMG_ERROR = 491;

	int CMPRESERVE_RESERVETIME_ERROR = 492;

	int CMPRESERVE_SELDATE_ERROR = 493;

	int CMPRESERVE_CREATE_OK = 494;

	int AUTHCOMPANY_NAME_ERROR = 495;

	int AUTHCOMPANY_TEL_ERROR = 496;

	int AUTHCOMPANY_USERNAME_ERROR = 497;

	int CMPACTOR_GENDER_ERROR = 498;

	int CMPOTHERINFO_SVRRATE_ERR = 499;

	int CMPRESERVE_USERNAME_ERROR = 500;

	int CMPOTHERINFO_DURATION_ERROR = 501;

	int COMPANY_SNAME_ERROR = 502;

	int CMPRESERVE_MOBILE_ERROR = 503;

	int CMPACTORCMT_CONTENT_ERROR = 504;

	int TB_USER_NICK_DUPLICATE = 505;

	int TB_USER_EMAIL_DUPLICATE = 506;

	int TB_USER_NICK_ERROR = 507;

	int TB_USER_GENDER_ERROR = 508;

	int TB_USER_EMAIL_ERROR = 509;

	int TB_USER_CITYID_ERROR = 510;

	int TB_USER_TAOBAO_NICK_ERROR = 511;

	int TB_USER_REPWD_ERROR = 512;

	int TB_USER_CODE_ERROR = 513;

	int TB_USER_PWD_ERROR = 514;

	int TB_USER_LOGIN_PWD_ERROR = 515;

	int TB_USER_LOGIN_INPUT_ERROR = 516;

	int API_SINA_APP_TIMEOUT = 517;

	int API_TAOBAO_APP_TIMEOUT = 518;

	int TB_ITEM_CMT_CONTENT_ERROR = 519;

	int TB_ITEM_CMT_REPLY_CONTENT_ERROR = 520;

	int API_TAOBAO_ITEM_NOT_EXIST = 521;

	int API_SINA_USER_EXIST = 522;

	int TB_ASK_TITLE_ERROR = 523;

	int TB_ASK_CONTENT_ERROR = 524;

	int TB_ANSWER_CONTENT_ERROR = 525;

	int TB_ASK_CAT_NAME_ERROR = 526;

	int TB_ASK_CAT_NAME_DUPLICATE_ERROR = 527;

	int TB_ASK_CID_ERROR = 528;

	int CMPCONTACT_NAME_ERROR = 529;

	int CMPUSERTABLEDATA_TITLE_ERROR = 530;

	int CMPUSERTABLEFIELD_NAME_ERROR = 531;

	int CMPUSERTABLEDATAOPTION_DATA_ERROR = 532;

	int CMPUSERTABLEDATAVALUE_DATA_TEXT_ERROR = 533;

	int CMPUSERTABLEDATAVALUE_DATA_TEXTAREA_ERROR = 534;

	int CMPUSERTABLEDATAVALUE_DATA_OPTION_ERROR = 535;
}