ALTER TABLE iwant.project MODIFY COLUMN descr VARCHAR(3000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE iwant.project MODIFY COLUMN neardescr VARCHAR(1000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE iwant.project MODIFY COLUMN descr VARCHAR(5000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
 MODIFY COLUMN neardescr VARCHAR(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
